name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  lint:
    strategy:
      matrix:
        node: ['14']

    runs-on: ubuntu-latest

    name: Lint node ${{ matrix.node }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run linter
        run: yarn lint
