name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    strategy:
      matrix:
        node: ['lts/*']
        platform: ['ubuntu-latest']

    runs-on: ${{ matrix.platform }}

    env:
      NEXT_PUBLIC_APP_URL: 'http://localhost:3000'

    name: Test node ${{ matrix.node }} ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test:cov --ci

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: ${{ env.NEXT_PUBLIC_APP_URL }}
          command: yarn test:e2e
          browser: chrome
